/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import logica.Lectura;
import logica.Main;

/**
 *
 * @author coram
 */
public class Ventana extends javax.swing.JFrame {
    
    //---------------------------- ATTRIBUTOS ----------------------------------
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup = new javax.swing.ButtonGroup();
        pan = new javax.swing.JPanel();
        panTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panMedio = new javax.swing.JPanel();
        lblPrimerNumero = new javax.swing.JLabel();
        lblSegundoNumero = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        rbSumatorio = new javax.swing.JRadioButton();
        rbProductorio = new javax.swing.JRadioButton();
        rbExponencial = new javax.swing.JRadioButton();
        panResultado = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pan.setBackground(new java.awt.Color(255, 255, 255));
        pan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panTitulo.setBackground(new java.awt.Color(255, 204, 255));
        panTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("Calculadora II");
        panTitulo.add(lblTitulo);

        panMedio.setBackground(new java.awt.Color(255, 255, 255));
        panMedio.setLayout(new java.awt.GridBagLayout());

        lblPrimerNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrimerNumero.setForeground(new java.awt.Color(51, 51, 51));
        lblPrimerNumero.setText("Introduzca el segundo número: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 20, 0, 0);
        panMedio.add(lblPrimerNumero, gridBagConstraints);

        lblSegundoNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSegundoNumero.setForeground(new java.awt.Color(51, 51, 51));
        lblSegundoNumero.setText("Introduzca el primer número: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 20, 0, 0);
        panMedio.add(lblSegundoNumero, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 91;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 7, 0, 6);
        panMedio.add(txtA, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 6);
        panMedio.add(txtB, gridBagConstraints);

        btnCalcular.setBackground(new java.awt.Color(255, 204, 255));
        btnCalcular.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(51, 51, 51));
        btnCalcular.setText("¡Calcula!");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 142;
        gridBagConstraints.ipady = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 6, 6);
        panMedio.add(btnCalcular, gridBagConstraints);

        buttonGroup.add(rbSumatorio);
        rbSumatorio.setForeground(new java.awt.Color(51, 51, 51));
        rbSumatorio.setText("Sumatorio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 20, 0, 0);
        panMedio.add(rbSumatorio, gridBagConstraints);

        buttonGroup.add(rbProductorio);
        rbProductorio.setForeground(new java.awt.Color(51, 51, 51));
        rbProductorio.setText("Productorio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 0, 0);
        panMedio.add(rbProductorio, gridBagConstraints);

        buttonGroup.add(rbExponencial);
        rbExponencial.setForeground(new java.awt.Color(51, 51, 51));
        rbExponencial.setText("Exponencial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 6, 0);
        panMedio.add(rbExponencial, gridBagConstraints);

        panResultado.setBackground(new java.awt.Color(255, 204, 255));
        panResultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblResultado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblResultado.setText("0");
        lblResultado.setToolTipText("");
        panResultado.add(lblResultado);

        javax.swing.GroupLayout panLayout = new javax.swing.GroupLayout(pan);
        pan.setLayout(panLayout);
        panLayout.setHorizontalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panMedio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panLayout.setVerticalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLayout.createSequentialGroup()
                .addComponent(panTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(panResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        String lectura1 = Lectura.validaEntero(txtA.getText());
        String lectura2 = Lectura.validaEntero(txtB.getText());
        
        if (lectura1.equals("ERROR") || lectura2.equals("ERROR")) {
            lblResultado.setText("ERROR: introduce enteros");
        }  else {
            int a = Integer.parseInt(txtA.getText());
            int b = Integer.parseInt(txtB.getText());
            
            mostrarRresultados(a, b);
  
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    //------------------------- MÉTODOS DE CLASES ------------------------------
    public void mostrarRresultados(int a, int b) {
        long resultado = 0;
        if (rbSumatorio.isSelected()) {
            resultado = Main.Sumatorio(a, b);
        }
        if (rbProductorio.isSelected()) {
            resultado = Main.Productorio(a, b);
        }
        if (rbExponencial.isSelected()) {
            resultado = Main.Exponencial(a, b);
        }
        lblResultado.setText("Resultado = " + resultado);
    } // calcularResultados(int a, int b)

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel lblPrimerNumero;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblSegundoNumero;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pan;
    private javax.swing.JPanel panMedio;
    private javax.swing.JPanel panResultado;
    private javax.swing.JPanel panTitulo;
    private javax.swing.JRadioButton rbExponencial;
    private javax.swing.JRadioButton rbProductorio;
    private javax.swing.JRadioButton rbSumatorio;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    // End of variables declaration//GEN-END:variables
}
