/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import logica.Main;

/**
 *
 * @author 🌟 Coraima Mera Rodríguez 🌟
 */
public class Ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setTitle("Ejercicio 11 – Loteria Primitiva"); // Definimos el nombre de la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pan = new javax.swing.JPanel();
        panCabeza = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        txtLogo = new javax.swing.JLabel();
        panNumeros = new javax.swing.JPanel();
        n1 = new javax.swing.JLabel();
        n2 = new javax.swing.JLabel();
        n3 = new javax.swing.JLabel();
        n4 = new javax.swing.JLabel();
        n5 = new javax.swing.JLabel();
        n6 = new javax.swing.JLabel();
        panbtn = new javax.swing.JPanel();
        btn = new javax.swing.JButton();
        panPie = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pan.setBackground(new java.awt.Color(255, 204, 255));

        panCabeza.setBackground(new java.awt.Color(255, 204, 255));

        txtTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("LA PRIMITIVA");

        txtLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo_La_Primitiva.png"))); // NOI18N

        javax.swing.GroupLayout panCabezaLayout = new javax.swing.GroupLayout(panCabeza);
        panCabeza.setLayout(panCabezaLayout);
        panCabezaLayout.setHorizontalGroup(
            panCabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );
        panCabezaLayout.setVerticalGroup(
            panCabezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCabezaLayout.createSequentialGroup()
                .addComponent(txtLogo)
                .addGap(0, 0, 0)
                .addComponent(txtTitulo))
        );

        panNumeros.setBackground(new java.awt.Color(255, 204, 255));

        n1.setBackground(new java.awt.Color(255, 255, 255));
        n1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        n1.setForeground(new java.awt.Color(255, 255, 255));
        n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n1.setText("00");
        n1.setAlignmentX(0.5F);
        n1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        n1.setPreferredSize(new java.awt.Dimension(35, 45));
        panNumeros.add(n1);

        n2.setBackground(new java.awt.Color(255, 255, 255));
        n2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        n2.setForeground(new java.awt.Color(255, 255, 255));
        n2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n2.setText("00");
        n2.setAlignmentX(0.5F);
        n2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        n2.setPreferredSize(new java.awt.Dimension(35, 45));
        panNumeros.add(n2);

        n3.setBackground(new java.awt.Color(255, 255, 255));
        n3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        n3.setForeground(new java.awt.Color(255, 255, 255));
        n3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n3.setText("00");
        n3.setAlignmentX(0.5F);
        n3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        n3.setPreferredSize(new java.awt.Dimension(35, 45));
        panNumeros.add(n3);

        n4.setBackground(new java.awt.Color(255, 255, 255));
        n4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        n4.setForeground(new java.awt.Color(255, 255, 255));
        n4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n4.setText("00");
        n4.setAlignmentX(0.5F);
        n4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        n4.setPreferredSize(new java.awt.Dimension(35, 45));
        panNumeros.add(n4);

        n5.setBackground(new java.awt.Color(255, 255, 255));
        n5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        n5.setForeground(new java.awt.Color(255, 255, 255));
        n5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n5.setText("00");
        n5.setAlignmentX(0.5F);
        n5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        n5.setPreferredSize(new java.awt.Dimension(35, 45));
        panNumeros.add(n5);

        n6.setBackground(new java.awt.Color(255, 255, 255));
        n6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        n6.setForeground(new java.awt.Color(255, 255, 255));
        n6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        n6.setText("00");
        n6.setAlignmentX(0.5F);
        n6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        n6.setPreferredSize(new java.awt.Dimension(35, 45));
        panNumeros.add(n6);

        panbtn.setBackground(new java.awt.Color(255, 204, 255));

        btn.setBackground(new java.awt.Color(255, 255, 255));
        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo_La_Primitiva.png"))); // NOI18N
        btn.setMargin(null);
        btn.setMaximumSize(null);
        btn.setMinimumSize(null);
        btn.setPreferredSize(null);
        btn.setSelected(true);
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        panbtn.add(btn);

        panPie.setBackground(new java.awt.Color(255, 204, 255));
        panPie.setLayout(new java.awt.GridBagLayout());

        txt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setText("Juegue responsablemente.");
        txt1.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 48, 0, 48);
        panPie.add(txt1, gridBagConstraints);

        txt2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt2.setForeground(new java.awt.Color(0, 153, 0));
        txt2.setText("Para mayores de 18 años.");
        txt2.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 53, 0, 0);
        panPie.add(txt2, gridBagConstraints);

        javax.swing.GroupLayout panLayout = new javax.swing.GroupLayout(pan);
        pan.setLayout(panLayout);
        panLayout.setHorizontalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panPie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panCabeza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panLayout.setVerticalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panCabeza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panPie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        Main.selccionarNumeros(n1, n2, n3, n4, n5, n6);
    }//GEN-LAST:event_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel n2;
    private javax.swing.JLabel n3;
    private javax.swing.JLabel n4;
    private javax.swing.JLabel n5;
    private javax.swing.JLabel n6;
    private javax.swing.JPanel pan;
    private javax.swing.JPanel panCabeza;
    private javax.swing.JPanel panNumeros;
    private javax.swing.JPanel panPie;
    private javax.swing.JPanel panbtn;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
