/*Ejercicio 06.05
Crear la BDD “TENIS” y añadir las siguientes tablas. Las claves primarias
están subrayadas y las claves ajenas se especifican con FK.
Restricciones de integridad: El borrado de registros referenciados será en
cascada, y las modificaciones de registros ref. estarán restringidas*/

DROP DATABASE IF EXISTS TENIS;
CREATE DATABASE TENIS;
USE TENIS;

DROP TABLE IF EXISTS PARTICIPA;
DROP TABLE IF EXISTS TORNEO;
DROP TABLE IF EXISTS NOMBRES_TORNEO;
DROP TABLE IF EXISTS ENTRENADOR;
DROP TABLE IF EXISTS TENISTA;

/*R1 = Tabla TENISTA (NUMTEN(CLAVE PRIMARIA), APELLIDO, NOMBRE, NACION,
CIUDAD, PUESTO, DESCRIPCION, FCHNAC)
• Ningún atributo puede tomar valor nulo.
• NUMTEN es numérico entero (1-999). AUTOINCREMENT.
• APELLIDO y NOMBRE: Tipo carácter de 50 caracteres máximo.
• NACION y CIUDAD: Tipo carácter de 20 caracteres máximo.
• PUESTO: Entero (1-999). No se puede repetir.
• DESCRIPCION: Cadena variable (1-1000 caracteres).
• FCHNAC: Tipo fecha.*/

CREATE TABLE TENISTA
(
    NUMTEN        SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    APELLIDO      VARCHAR(50) NOT NULL,
    NOMBRE        VARCHAR(50) NOT NULL,
    NACION        VARCHAR(20) NOT NULL,
    CIUDAD        VARCHAR(20) NOT NULL,
    PUESTO        SMALLINT UNSIGNED NOT NULL UNIQUE,
    DESCRIPCION   VARCHAR(1000) NOT NULL,
    FCHNAC        DATE NOT NULL,
    CONSTRAINT CK_PUESTO CHECK (PUESTO BETWEEN 1 AND 999)
) ENGINE = InnoDB;

/*R2 = Tabla ENTRENADOR (NUMENTR(CLAVE PRIMARIA), APELLIDO, NOMBRE,
NACION, FCHNAC, CODTENISTA (FK1))
• Ningún atributo puede tomar valor nulo.
• NUMENTR es numérico entero (1-999). AUTOINCREMENT.
• APELLIDO y NOMBRE: Tipo carácter de 50 caracteres máximo.
• NACION: Tipo carácter de 20 caracteres máximo.
• FCHNAC: Tipo fecha.
• CODTENISTA es clave foránea referenciada a TENISTA.*/

CREATE TABLE ENTRENADOR
(
    NUMENTR      SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    APELLIDO     VARCHAR(50) NOT NULL,
    NOMBRE       VARCHAR(50) NOT NULL,
    NACION       VARCHAR(20) NOT NULL,
    FCHNAC       DATE NOT NULL,
    CODTENISTA   SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT FK_ENTRENADOR_TENISTA FOREIGN KEY (CODTENISTA)
        REFERENCES TENISTA(NUMTEN)
        ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE = InnoDB;

/*R3 = Tabla NOMBRES_TORNEO (CODIGO(CLAVE PRIMARIA), NOMBRE, CATEGORIA)
• Ningún atributo puede tomar valor nulo.
• CODIGO es numérico entero (1-999). AUTOINCREMENT.
• NOMBRE: Tipo carácter de 50 caracteres máximo.
• CATEGORIA: Sólo puede tomar los valores:
  GRAND SLAM, ATP WORLD TOURS, COPA DAVIS, ATP CHALLENGER, FUTURE*/

CREATE TABLE NOMBRES_TORNEO
(
    CODIGO     SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE     VARCHAR(50) NOT NULL,
    CATEGORIA  VARCHAR(20) NOT NULL,
    CONSTRAINT CK_CATEGORIA CHECK (CATEGORIA IN
        ('GRAND SLAM','ATP WORLD TOURS','COPA DAVIS','ATP CHALLENGER','FUTURE'))
) ENGINE = InnoDB;

/*R4 = Tabla TORNEO (FECHA(CLAVE PRIMARIA), CODTORNEO (FK3), PREMIO)
• Ningún atributo puede tomar valor nulo.
• FECHA: Tipo fecha.
• CODTORNEO: Entero (1-999). Clave foránea.
• PREMIO: Numérico real (0.00 - 999999999.99), con 2 decimales.*/

CREATE TABLE TORNEO
(
    FECHA        DATE NOT NULL PRIMARY KEY,
    CODTORNEO    SMALLINT UNSIGNED NOT NULL,
    PREMIO       DECIMAL(11,2) NOT NULL,
    CONSTRAINT CK_PREMIO CHECK (PREMIO BETWEEN 0.00 AND 999999999.99),
    CONSTRAINT FK_TORNEO_NOMBRE FOREIGN KEY (CODTORNEO)
        REFERENCES NOMBRES_TORNEO(CODIGO)
        ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE = InnoDB;

/*R5 = Tabla PARTICIPA (NUMTEN (FK1), FECHA (FK4), ORDEN)
• Ningún atributo puede tomar valor nulo, excepto ORDEN.
• NUMTEN y FECHA forman la clave primaria.
• NUMTEN: Entero (1-999). Clave foránea.
• FECHA: Tipo fecha. Clave foránea.
• ORDEN: Entero (0-250). Puede ser NULL.
  0 indica descalificado o abandono.*/

CREATE TABLE PARTICIPA
(
    NUMTEN    SMALLINT UNSIGNED NOT NULL,
    FECHA     DATE NOT NULL,
    ORDEN     SMALLINT UNSIGNED NULL,
    PRIMARY KEY (NUMTEN, FECHA),
    CONSTRAINT CK_ORDEN CHECK (ORDEN BETWEEN 0 AND 250 OR ORDEN IS NULL),
    CONSTRAINT FK_PARTICIPA_TENISTA FOREIGN KEY (NUMTEN)
        REFERENCES TENISTA(NUMTEN)
        ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT FK_PARTICIPA_TORNEO FOREIGN KEY (FECHA)
        REFERENCES TORNEO(FECHA)
        ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE = InnoDB;