/*Ejercicio 06.02
Crear la BDD “ELECTIENDA” y añadir las siguientes tablas. Las claves primarias
están subrayadas y las claves ajenas se especifican con FK.
Restricciones de integridad: El borrado de registros referenciados no está
permitido, y las modificaciones de registros ref. se harán en cascada*/

DROP DATABASE IF EXISTS ELECTIENDA;
CREATE DATABASE ELECTIENDA;
use ELECTIENDA;

DROP TABLE IF EXISTS TIENDA;
DROP TABLE IF EXISTS ELECTROS;
DROP TABLE IF EXISTS CLIENTES;
DROP TABLE IF EXISTS PRECIOS;
DROP TABLE IF EXISTS VENDEDOR;
DROP TABLE IF EXISTS VENTAS;

/*R1 = Tabla TIENDA (CODTIENDA(CLAVE PRIMARIA), NOMTIENDA, DIREC_TIENDA, TLF_TIENDA)
• Ningún atributo puede tomar valor nulo.
• La columna CODTIENDA es numérico entero. Su valor tiene que ser superior a 999
e inferior a 10000.
• NOMTIENDA y DIREC_TIENDA: Tipo carácter de 100 caracteres.
• TLF_TIENDA: Tipo carácter de 9 caracteres.*/

CREATE TABLE TIENDA
(
	CODTIENDA		SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    NOMTIENDA		VARCHAR(100) NOT NULL,
    DIREC_TIENDA	VARCHAR(100) NOT NULL,
    TLF_TIENDA		CHAR(9) NOT NULL,
    CONSTRAINT CK CHECK (CODTIENDA BETWEEN 999 AND 10000)
) engine = InnoDB;

/*R2 = Tabla ELECTROS (CODELECT(CLAVE PRIMARIA), DESCRIPCION)
• Ningún atributo puede tomar valor nulo.
• CODELECT: Tipo carácter de 9 caracteres.
• DESCRIPCION: Tipo carácter de 100 caracteres.*/

CREATE TABLE ELECTROS
(
	CODELECT		CHAR(9) NOT NULL PRIMARY KEY,
    DESCRIPCION		VARCHAR(100) NOT NULL
) engine = InnoDB;

/*R3 = Tabla CLIENTES (COD_CLI(CLAVE PRIMARIA), NOM_CLI, DOMICILIO_CLI, TLF_CLI)
• Ningún atributo puede tomar valor nulo.
• COD_CLI es numérico entero. Su valor tiene que ser superior 10000.
• NOM_CLI y DOMICILIO_CLI: Tipo carácter de 100 caracteres.
• TLF_CLI: Tipo carácter de 9 caracteres.*/

CREATE TABLE CLIENTES
(
	COD_CLI			SMALLINT UNSIGNED NOT NULL PRIMARY KEY CHECK (COD_CLI > 10000),
    NOM_CLI			VARCHAR(100) NOT NULL,
    DOMICILIO_CLI	VARCHAR(100) NOT NULL,
    TLF_CLI			CHAR(9) NOT NULL
) engine = InnoDB;

/*R4 = Tabla PRECIOS (CODELECT (FK2), CODTIENDA (FK1), PRECIO_UNIDAD)
• Ningún atributo puede tomar valor nulo.
• CODELECT es carácter de 9 caracteres.
• CODTIENDA es numérico entero. Su valor: > 999 y <10000.
• PRECIO_UNIDAD es numérico real, con dos decimales.*/

CREATE TABLE PRECIOS
(
	CODELECT		CHAR(9) NOT NULL,
    CODTIENDA		SMALLINT UNSIGNED NOT NULL,
    PRECIO_UNIDAD	DECIMAL(8,2) NOT NULL,
    PRIMARY KEY (CODELECT, CODTIENDA),
    CONSTRAINT FK_PRECIOS_ELECTROS FOREIGN KEY (CODELECT) REFERENCES 
		ELECTROS(CODELECT) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT FK_PRECIOS_TIENDA FOREIGN KEY (CODTIENDA) REFERENCES
		TIENDA(CODTIENDA) ON DELETE RESTRICT ON UPDATE CASCADE
) engine = InnoDB;

/*R5 = Tabla VENDEDOR (NIF_VDDOR(CLAVE PRIMARIA), NOMBRE_VDDOR, TLF_VDDOR)
• Ningún atributo puede tomar valor nulo.
• NIF_VDDOR: Tipo carácter de 9 caracteres.
• NOMBRE_VDDOR: Tipo carácter de 100 caracteres.
• TLF_VDDOR: Tipo carácter de 9 caracteres. Su valor no se puede repetir.*/

CREATE TABLE VENDEDOR
(
	NIF_VDDOR	 	CHAR(9) NOT NULL PRIMARY KEY,
	NOMBRE_VDDOR	VARCHAR(100) NOT NULL,
	TLF_VDDOR		CHAR(9) NOT NULL UNIQUE
) engine = InnoDB;

/*R6 = Tabla VENTAS ( ( { CODELECT (FK2) , CODTIENDA (FK1) } (FK4),
COD_CLI (FK3), FECHAHORA_VENTA, UNIDADES_VENDIDAS, DESCUENTO, NIF_VDDOR (FK5))
• Ningún atributo puede tomar valor nulo.
• NIF_VENDEDOR y CODELECT son de tipo carácter de 9 caracteres.
• CODTIENDA, COD_CLI y UNIDADES_VENDIDAS son numéricos enteros.
• UNIDADES_VENDIDAS tienen que valer 1 como mínimo.
• DESCUENTO es numérico real, con dos decimales.*/

CREATE TABLE VENTAS
(
    CODELECT			CHAR(9) NOT NULL,
    CODTIENDA			SMALLINT UNSIGNED NOT NULL,
    COD_CLI				SMALLINT UNSIGNED NOT NULL,
    FECHAHORA_VENTA		TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIDADES_VENDIDAS	INT UNSIGNED NOT NULL CHECK ( UNIDADES_VENDIDAS > 0),
    DESCUENTO 			DECIMAL(5,2) NOT NULL,
	NIF_VDDOR			CHAR(9) NOT NULL,    
    PRIMARY KEY (CODELECT, CODTIENDA, COD_CLI, FECHAHORA_VENTA),
    CONSTRAINT FK_VENTAS_ELECTROS FOREIGN KEY (CODELECT) REFERENCES 
		ELECTROS(CODELECT) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT FK_VENTAS_TIENDA FOREIGN KEY (CODTIENDA) REFERENCES 
		TIENDA(CODTIENDA) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT FK_VENTAS_CLIENTES FOREIGN KEY (COD_CLI) REFERENCES 
		CLIENTES(COD_CLI) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT FK_VENTAS_VENDEDOR FOREIGN KEY (NIF_VDDOR) REFERENCES 
		VENDEDOR(NIF_VDDOR) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT FK_VENTAS_PRECIOS FOREIGN KEY (CODELECT, CODTIENDA) REFERENCES 
		PRECIOS(CODELECT, CODTIENDA) ON DELETE RESTRICT ON UPDATE CASCADE
) engine = InnoDB;