/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import logica.Main;

/**
 *
 * @author 🌟 Coraima Mera Rodríguez 🌟
 */
public class Ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());
    
    // Inicializamos la imagen de la ventana emergente
    private ImageIcon img = new ImageIcon(getClass().getResource("/img/Hamburguesa.png"));

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setTitle("CASO PRÁCTICO – BURGER MENU APP - Coraima Mera Rodriguez"); // Definimos el nombre de la ventana
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/Hamburguesa.png")).getImage()); // Ponemos imagen a la ventana princial
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpHamburguesa = new javax.swing.ButtonGroup();
        btnGrpPan = new javax.swing.ButtonGroup();
        btnGrpPatatas = new javax.swing.ButtonGroup();
        btnGrpBebida = new javax.swing.ButtonGroup();
        pan = new javax.swing.JPanel();
        panTitulo = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        panProductos = new javax.swing.JPanel();
        panHamburguesa = new javax.swing.JPanel();
        txtHamburguesa = new javax.swing.JLabel();
        imgHamburguesa = new javax.swing.JLabel();
        txtTipo1 = new javax.swing.JLabel();
        rdbtnHPollo = new javax.swing.JRadioButton();
        rdbtnHCerdo = new javax.swing.JRadioButton();
        rdbtnHTernera = new javax.swing.JRadioButton();
        rdbtnHVegana = new javax.swing.JRadioButton();
        panPan = new javax.swing.JPanel();
        txtPan = new javax.swing.JLabel();
        imgPan = new javax.swing.JLabel();
        txtTipo2 = new javax.swing.JLabel();
        rdbtnPNormal = new javax.swing.JRadioButton();
        rdbtnPIntegral = new javax.swing.JRadioButton();
        rdbtnPCenteno = new javax.swing.JRadioButton();
        panPatatas = new javax.swing.JPanel();
        txtPatatas = new javax.swing.JLabel();
        imgPatatas = new javax.swing.JLabel();
        txtTipo3 = new javax.swing.JLabel();
        rdbtnPFritas = new javax.swing.JRadioButton();
        rdbtnPGajo = new javax.swing.JRadioButton();
        rdbtnPCaseras = new javax.swing.JRadioButton();
        panBebida = new javax.swing.JPanel();
        txtBebida = new javax.swing.JLabel();
        imgBebida = new javax.swing.JLabel();
        txtTipo4 = new javax.swing.JLabel();
        rdbtnBCola = new javax.swing.JRadioButton();
        rdbtnBNaranja = new javax.swing.JRadioButton();
        rdbtnBLimon = new javax.swing.JRadioButton();
        rdbtnBAgua = new javax.swing.JRadioButton();
        rdbtnBCerveza = new javax.swing.JRadioButton();
        panAdicionales = new javax.swing.JPanel();
        panExtras = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        CheckBoxHamburguesa = new javax.swing.JCheckBox();
        CheckBoxQueso = new javax.swing.JCheckBox();
        CheckBoxPatatas = new javax.swing.JCheckBox();
        panSalsas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CheckBoxKetchup = new javax.swing.JCheckBox();
        CheckBoxBarbacoa = new javax.swing.JCheckBox();
        CheckBoxMostaza = new javax.swing.JCheckBox();
        CheckBoxThai = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        ComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        panBtn = new javax.swing.JPanel();
        lblPrecio = new javax.swing.JLabel();
        btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pan.setBackground(new java.awt.Color(255, 255, 255));

        panTitulo.setBackground(new java.awt.Color(255, 255, 255));
        panTitulo.setForeground(new java.awt.Color(255, 204, 255));
        panTitulo.setLayout(new java.awt.BorderLayout());

        txtTitulo.setBackground(new java.awt.Color(255, 255, 255));
        txtTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(51, 51, 51));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText(" BURGER MENU APP");
        panTitulo.add(txtTitulo, java.awt.BorderLayout.CENTER);

        panProductos.setBackground(new java.awt.Color(255, 255, 255));
        panProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panProductos.setLayout(new java.awt.GridLayout(1, 0));

        panHamburguesa.setBackground(new java.awt.Color(255, 255, 255));

        txtHamburguesa.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        txtHamburguesa.setForeground(new java.awt.Color(51, 51, 51));
        txtHamburguesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHamburguesa.setText("HAMBURGUESA");

        imgHamburguesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgHamburguesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Carne.png"))); // NOI18N

        txtTipo1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        txtTipo1.setForeground(new java.awt.Color(51, 51, 51));
        txtTipo1.setText("  Tipos:");

        btnGrpHamburguesa.add(rdbtnHPollo);
        rdbtnHPollo.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnHPollo.setSelected(true);
        rdbtnHPollo.setText("Pollo");
        rdbtnHPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnHPolloActionPerformed(evt);
            }
        });

        btnGrpHamburguesa.add(rdbtnHCerdo);
        rdbtnHCerdo.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnHCerdo.setText("Cerdo");
        rdbtnHCerdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnHCerdoActionPerformed(evt);
            }
        });

        btnGrpHamburguesa.add(rdbtnHTernera);
        rdbtnHTernera.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnHTernera.setText("Ternera (+1€)");
        rdbtnHTernera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnHTerneraActionPerformed(evt);
            }
        });

        btnGrpHamburguesa.add(rdbtnHVegana);
        rdbtnHVegana.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnHVegana.setText("Vegana (+1€)");
        rdbtnHVegana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnHVeganaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panHamburguesaLayout = new javax.swing.GroupLayout(panHamburguesa);
        panHamburguesa.setLayout(panHamburguesaLayout);
        panHamburguesaLayout.setHorizontalGroup(
            panHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtHamburguesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imgHamburguesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtTipo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHamburguesaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdbtnHVegana, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnHTernera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnHCerdo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnHPollo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        panHamburguesaLayout.setVerticalGroup(
            panHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHamburguesaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtHamburguesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgHamburguesa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnHPollo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnHCerdo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnHTernera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnHVegana)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panProductos.add(panHamburguesa);

        panPan.setBackground(new java.awt.Color(204, 204, 204));

        txtPan.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        txtPan.setForeground(new java.awt.Color(51, 51, 51));
        txtPan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPan.setText("PAN");

        imgPan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pan.png"))); // NOI18N

        txtTipo2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        txtTipo2.setForeground(new java.awt.Color(51, 51, 51));
        txtTipo2.setText("  Tipos:");

        btnGrpPan.add(rdbtnPNormal);
        rdbtnPNormal.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnPNormal.setSelected(true);
        rdbtnPNormal.setText("Normal");
        rdbtnPNormal.setMaximumSize(new java.awt.Dimension(93, 21));
        rdbtnPNormal.setMinimumSize(new java.awt.Dimension(93, 21));
        rdbtnPNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnPNormalActionPerformed(evt);
            }
        });

        btnGrpPan.add(rdbtnPIntegral);
        rdbtnPIntegral.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnPIntegral.setText("Integral");
        rdbtnPIntegral.setMaximumSize(new java.awt.Dimension(93, 21));
        rdbtnPIntegral.setMinimumSize(new java.awt.Dimension(93, 21));
        rdbtnPIntegral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnPIntegralActionPerformed(evt);
            }
        });

        btnGrpPan.add(rdbtnPCenteno);
        rdbtnPCenteno.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnPCenteno.setText("Centeno");
        rdbtnPCenteno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnPCentenoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panPanLayout = new javax.swing.GroupLayout(panPan);
        panPan.setLayout(panPanLayout);
        panPanLayout.setHorizontalGroup(
            panPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imgPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtTipo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdbtnPIntegral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnPCenteno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnPNormal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panPanLayout.setVerticalGroup(
            panPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtPan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgPan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnPNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnPIntegral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnPCenteno)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        panProductos.add(panPan);

        panPatatas.setBackground(new java.awt.Color(255, 255, 255));

        txtPatatas.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        txtPatatas.setForeground(new java.awt.Color(51, 51, 51));
        txtPatatas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPatatas.setText("PATATAS");

        imgPatatas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPatatas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Patatas.png"))); // NOI18N
        imgPatatas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgPatatas.setFocusable(false);

        txtTipo3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        txtTipo3.setForeground(new java.awt.Color(51, 51, 51));
        txtTipo3.setText("  Tipos:");

        btnGrpPatatas.add(rdbtnPFritas);
        rdbtnPFritas.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnPFritas.setSelected(true);
        rdbtnPFritas.setText("Fritas");
        rdbtnPFritas.setMaximumSize(new java.awt.Dimension(93, 21));
        rdbtnPFritas.setMinimumSize(new java.awt.Dimension(93, 21));
        rdbtnPFritas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnPFritasActionPerformed(evt);
            }
        });

        btnGrpPatatas.add(rdbtnPGajo);
        rdbtnPGajo.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnPGajo.setText("Gajo");
        rdbtnPGajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnPGajoActionPerformed(evt);
            }
        });

        btnGrpPatatas.add(rdbtnPCaseras);
        rdbtnPCaseras.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnPCaseras.setText("Caseras (+1€)");
        rdbtnPCaseras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnPCaserasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panPatatasLayout = new javax.swing.GroupLayout(panPatatas);
        panPatatas.setLayout(panPatatasLayout);
        panPatatasLayout.setHorizontalGroup(
            panPatatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPatatas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imgPatatas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtTipo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPatatasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panPatatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdbtnPGajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnPFritas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnPCaseras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panPatatasLayout.setVerticalGroup(
            panPatatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPatatasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtPatatas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgPatatas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnPFritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnPGajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnPCaseras)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panProductos.add(panPatatas);

        panBebida.setBackground(new java.awt.Color(204, 204, 204));

        txtBebida.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        txtBebida.setForeground(new java.awt.Color(51, 51, 51));
        txtBebida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBebida.setText("BEBIDA");

        imgBebida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bebida.png"))); // NOI18N

        txtTipo4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        txtTipo4.setForeground(new java.awt.Color(51, 51, 51));
        txtTipo4.setText("  Tipos:");

        btnGrpBebida.add(rdbtnBCola);
        rdbtnBCola.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnBCola.setSelected(true);
        rdbtnBCola.setText("Refresco de cola");
        rdbtnBCola.setToolTipText("");

        btnGrpBebida.add(rdbtnBNaranja);
        rdbtnBNaranja.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnBNaranja.setText("Refresco de naranja");
        rdbtnBNaranja.setToolTipText("");

        btnGrpBebida.add(rdbtnBLimon);
        rdbtnBLimon.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnBLimon.setText("Refresco de limón");
        rdbtnBLimon.setToolTipText("");

        btnGrpBebida.add(rdbtnBAgua);
        rdbtnBAgua.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnBAgua.setText("Agua");
        rdbtnBAgua.setToolTipText("");

        btnGrpBebida.add(rdbtnBCerveza);
        rdbtnBCerveza.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnBCerveza.setText("Cerveza");
        rdbtnBCerveza.setToolTipText("");

        javax.swing.GroupLayout panBebidaLayout = new javax.swing.GroupLayout(panBebida);
        panBebida.setLayout(panBebidaLayout);
        panBebidaLayout.setHorizontalGroup(
            panBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imgBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtTipo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBebidaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdbtnBNaranja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnBCola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnBLimon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnBAgua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnBCerveza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panBebidaLayout.setVerticalGroup(
            panBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBebidaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtBebida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnBCola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnBNaranja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnBLimon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnBAgua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbtnBCerveza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panProductos.add(panBebida);

        panAdicionales.setBackground(new java.awt.Color(204, 204, 204));
        panAdicionales.setLayout(new java.awt.BorderLayout());

        txt1.setText("Las opciones extra son:");

        CheckBoxHamburguesa.setText("Hamburguesa doble (+2 €)");
        CheckBoxHamburguesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxHamburguesaActionPerformed(evt);
            }
        });

        CheckBoxQueso.setText("Extra de queso (+0,50 €)");
        CheckBoxQueso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxQuesoActionPerformed(evt);
            }
        });

        CheckBoxPatatas.setText("Extra de patatas (+1 €)");
        CheckBoxPatatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxPatatasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panExtrasLayout = new javax.swing.GroupLayout(panExtras);
        panExtras.setLayout(panExtrasLayout);
        panExtrasLayout.setHorizontalGroup(
            panExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt1)
                    .addComponent(CheckBoxHamburguesa)
                    .addComponent(CheckBoxQueso)
                    .addComponent(CheckBoxPatatas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panExtrasLayout.setVerticalGroup(
            panExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxHamburguesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxQueso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxPatatas)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panAdicionales.add(panExtras, java.awt.BorderLayout.CENTER);

        jLabel3.setText("Las opciones adicionales son:");

        CheckBoxKetchup.setText("ketchup (+0,50)");
        CheckBoxKetchup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxKetchupActionPerformed(evt);
            }
        });

        CheckBoxBarbacoa.setText("barbacoa (+0,50)");
        CheckBoxBarbacoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxBarbacoaActionPerformed(evt);
            }
        });

        CheckBoxMostaza.setText("mostaza (+0,50)");
        CheckBoxMostaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxMostazaActionPerformed(evt);
            }
        });

        CheckBoxThai.setText("thai (+0,50)");
        CheckBoxThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxThaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panSalsasLayout = new javax.swing.GroupLayout(panSalsas);
        panSalsas.setLayout(panSalsasLayout);
        panSalsasLayout.setHorizontalGroup(
            panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSalsasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(CheckBoxKetchup)
                    .addComponent(CheckBoxBarbacoa)
                    .addComponent(CheckBoxThai)
                    .addComponent(CheckBoxMostaza))
                .addContainerGap(557, Short.MAX_VALUE))
        );
        panSalsasLayout.setVerticalGroup(
            panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSalsasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxKetchup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxBarbacoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxMostaza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxThai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panAdicionales.add(panSalsas, java.awt.BorderLayout.PAGE_START);

        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reparto a domicilio (precio estándar)", "Recogida en el local (-20% sobre el precio final)", " " }));
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Opciones de envio:");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBox, 0, 706, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panAdicionales.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        panBtn.setBackground(new java.awt.Color(255, 255, 255));
        panBtn.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        lblPrecio.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(51, 51, 51));
        lblPrecio.setText("TOTAL: 8 €");
        panBtn.add(lblPrecio);

        btn.setBackground(new java.awt.Color(51, 51, 51));
        btn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn.setForeground(new java.awt.Color(255, 255, 255));
        btn.setText("Comprar");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        panBtn.add(btn);

        javax.swing.GroupLayout panLayout = new javax.swing.GroupLayout(pan);
        pan.setLayout(panLayout);
        panLayout.setHorizontalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(panLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panAdicionales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panLayout.setVerticalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLayout.createSequentialGroup()
                .addComponent(panTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panAdicionales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        // Cuando se pulse el boton llamamos a una ventana emergente que a su vez llamara a factura y mostrara su contenido
        JOptionPane.showMessageDialog(this, Main.factura(generarFactura()), "Factura: Menu de hamburguesa", JOptionPane.PLAIN_MESSAGE, img);
    }//GEN-LAST:event_btnActionPerformed

    private void rdbtnHTerneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnHTerneraActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_rdbtnHTerneraActionPerformed

    private void rdbtnHVeganaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnHVeganaActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_rdbtnHVeganaActionPerformed

    private void rdbtnPCaserasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnPCaserasActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_rdbtnPCaserasActionPerformed

    private void CheckBoxKetchupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxKetchupActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_CheckBoxKetchupActionPerformed

    private void CheckBoxBarbacoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxBarbacoaActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_CheckBoxBarbacoaActionPerformed

    private void CheckBoxMostazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxMostazaActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_CheckBoxMostazaActionPerformed

    private void CheckBoxThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxThaiActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_CheckBoxThaiActionPerformed

    private void CheckBoxHamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxHamburguesaActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_CheckBoxHamburguesaActionPerformed

    private void CheckBoxQuesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxQuesoActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_CheckBoxQuesoActionPerformed

    private void CheckBoxPatatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxPatatasActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_CheckBoxPatatasActionPerformed

    private void rdbtnHPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnHPolloActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_rdbtnHPolloActionPerformed

    private void rdbtnHCerdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnHCerdoActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_rdbtnHCerdoActionPerformed

    private void rdbtnPNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnPNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnPNormalActionPerformed

    private void rdbtnPIntegralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnPIntegralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnPIntegralActionPerformed

    private void rdbtnPCentenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnPCentenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnPCentenoActionPerformed

    private void rdbtnPFritasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnPFritasActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_rdbtnPFritasActionPerformed

    private void rdbtnPGajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnPGajoActionPerformed
        // TODO add your handling code here:
        comprobacionMenu(); // Actualizamos el precio del label
    }//GEN-LAST:event_rdbtnPGajoActionPerformed

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed
        // TODO add your handling code here:
        // Depende de lo selecionado, ponemos si tiene descuento o no
        if (ComboBox.getSelectedIndex() == 0) Main.añadirDescuento(false);
        else Main.añadirDescuento(true);
    }//GEN-LAST:event_ComboBoxActionPerformed
    
    //------------------------- MÉTODOS DE CLASES ------------------------------
    public void comprobacionMenu() {
        
        // Reiniciamos el precio
        Main.reinicio();
        
        // Opciones del menu que añaden dinero extra
        if (rdbtnHTernera.isSelected()) Main.añadirExtras(1);
        if (rdbtnHVegana.isSelected()) Main.añadirExtras(1);
        if (rdbtnPCaseras.isSelected()) Main.añadirExtras(1);
        
        // Opciones de salsas
        if (CheckBoxKetchup.isSelected()) Main.añadirExtras(0.5);
        if (CheckBoxBarbacoa.isSelected()) Main.añadirExtras(0.5);
        if (CheckBoxMostaza.isSelected()) Main.añadirExtras(0.5);
        if (CheckBoxThai.isSelected()) Main.añadirExtras(0.5);
        
        // Extras en el menu
        if (CheckBoxHamburguesa.isSelected()) Main.añadirExtras(2);
        if (CheckBoxQueso.isSelected()) Main.añadirExtras(0.5);
        if (CheckBoxPatatas.isSelected()) Main.añadirExtras(1);
        
        // Actualizamos el precio del texto
        lblPrecio.setText("TOTAL: " + String.valueOf(Main.precioMenu()) + "€");
        
    } // comprobacionMenu()
    
    private String generarFactura() {

        // Empezamos la factura
        String pedido = "";

        // Añadimos la hamburguesa con su tipo
        pedido += "Hamburguesa: ";
        if (rdbtnHPollo.isSelected()) pedido += "Pollo";
        else if (rdbtnHCerdo.isSelected()) pedido += "Cerdo";
        else if (rdbtnHTernera.isSelected()) pedido += "Ternera (+1€)";
        else if (rdbtnHVegana.isSelected()) pedido += "Vegana (+1€)";

        // El pan
        pedido += "\nPan: ";
        if (rdbtnPNormal.isSelected()) pedido += "Normal";
        else if (rdbtnPIntegral.isSelected()) pedido += "Integral";
        else if (rdbtnPCenteno.isSelected()) pedido += "Centeno";

        // Las patatas
        pedido += "\nPatatas: ";
        if (rdbtnPFritas.isSelected()) pedido += "Fritas";
        else if (rdbtnPGajo.isSelected()) pedido += "Gajo";
        else if (rdbtnPCaseras.isSelected()) pedido += "Caseras (+1€)";

        // La bebida
        pedido += "\nBebida: ";
        if (rdbtnBCola.isSelected()) pedido += "Refresco de cola";
        else if (rdbtnBNaranja.isSelected()) pedido += "Refresco de naranja";
        else if (rdbtnBLimon.isSelected()) pedido += "Refresco de limón";
        else if (rdbtnBAgua.isSelected()) pedido += "Agua";
        else if (rdbtnBCerveza.isSelected()) pedido += "Cerveza";
        
        // Añadimos los extras que seleccione
        pedido += "\n\nExtras:\n";

        if (CheckBoxHamburguesa.isSelected()) pedido += "- Hamburguesa doble (+2€)\n";
        if (CheckBoxQueso.isSelected()) pedido += "- Extra queso (+0,50€)\n";
        if (CheckBoxPatatas.isSelected()) pedido += "- Extra patatas (+1€)\n";
        if (CheckBoxKetchup.isSelected()) pedido += "- Salsa ketchup (+0,50€)\n";
        if (CheckBoxBarbacoa.isSelected()) pedido += "- Salsa barbacoa (+0,50€)\n";
        if (CheckBoxMostaza.isSelected()) pedido += "- Salsa mostaza (+0,50€)\n";
        if (CheckBoxThai.isSelected())pedido += "- Salsa thai (+0,50€)\n";
        
        // Ponemos el pedido seleccionado
        pedido += "\nEntrega: " + ComboBox.getSelectedItem();

        // Y por ultimo devolvemos lo seleccionado
        return pedido;
        
    } // generarPedido()
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxBarbacoa;
    private javax.swing.JCheckBox CheckBoxHamburguesa;
    private javax.swing.JCheckBox CheckBoxKetchup;
    private javax.swing.JCheckBox CheckBoxMostaza;
    private javax.swing.JCheckBox CheckBoxPatatas;
    private javax.swing.JCheckBox CheckBoxQueso;
    private javax.swing.JCheckBox CheckBoxThai;
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JButton btn;
    private javax.swing.ButtonGroup btnGrpBebida;
    private javax.swing.ButtonGroup btnGrpHamburguesa;
    private javax.swing.ButtonGroup btnGrpPan;
    private javax.swing.ButtonGroup btnGrpPatatas;
    private javax.swing.JLabel imgBebida;
    private javax.swing.JLabel imgHamburguesa;
    private javax.swing.JLabel imgPan;
    private javax.swing.JLabel imgPatatas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JPanel pan;
    private javax.swing.JPanel panAdicionales;
    private javax.swing.JPanel panBebida;
    private javax.swing.JPanel panBtn;
    private javax.swing.JPanel panExtras;
    private javax.swing.JPanel panHamburguesa;
    private javax.swing.JPanel panPan;
    private javax.swing.JPanel panPatatas;
    private javax.swing.JPanel panProductos;
    private javax.swing.JPanel panSalsas;
    private javax.swing.JPanel panTitulo;
    private javax.swing.JRadioButton rdbtnBAgua;
    private javax.swing.JRadioButton rdbtnBCerveza;
    private javax.swing.JRadioButton rdbtnBCola;
    private javax.swing.JRadioButton rdbtnBLimon;
    private javax.swing.JRadioButton rdbtnBNaranja;
    private javax.swing.JRadioButton rdbtnHCerdo;
    private javax.swing.JRadioButton rdbtnHPollo;
    private javax.swing.JRadioButton rdbtnHTernera;
    private javax.swing.JRadioButton rdbtnHVegana;
    private javax.swing.JRadioButton rdbtnPCaseras;
    private javax.swing.JRadioButton rdbtnPCenteno;
    private javax.swing.JRadioButton rdbtnPFritas;
    private javax.swing.JRadioButton rdbtnPGajo;
    private javax.swing.JRadioButton rdbtnPIntegral;
    private javax.swing.JRadioButton rdbtnPNormal;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txtBebida;
    private javax.swing.JLabel txtHamburguesa;
    private javax.swing.JLabel txtPan;
    private javax.swing.JLabel txtPatatas;
    private javax.swing.JLabel txtTipo1;
    private javax.swing.JLabel txtTipo2;
    private javax.swing.JLabel txtTipo3;
    private javax.swing.JLabel txtTipo4;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
