/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import logica.Main;

/**
 *
 * @author usuario
 */
public class Ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setTitle("Ejercicio 6 – Dados de Rol"); // Definimos el nombre de la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        pan = new javax.swing.JPanel();
        panTitulo = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        panContenido = new javax.swing.JPanel();
        txtResultado = new javax.swing.JLabel();
        btn6caras = new javax.swing.JButton();
        btn8caras = new javax.swing.JButton();
        btn10caras = new javax.swing.JButton();
        btn20caras = new javax.swing.JButton();
        btn12caras = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);

        pan.setBackground(new java.awt.Color(255, 255, 255));

        panTitulo.setBackground(new java.awt.Color(255, 204, 255));
        panTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTitulo.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(51, 51, 51));
        txtTitulo.setText("Números Aleatorios");
        panTitulo.add(txtTitulo);

        panContenido.setBackground(new java.awt.Color(255, 255, 255));
        panContenido.setLayout(new java.awt.GridBagLayout());

        txtResultado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(51, 51, 51));
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtResultado.setText("Número generado: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        panContenido.add(txtResultado, gridBagConstraints);

        btn6caras.setBackground(new java.awt.Color(255, 204, 255));
        btn6caras.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btn6caras.setForeground(new java.awt.Color(51, 51, 51));
        btn6caras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dado-6caras.png"))); // NOI18N
        btn6caras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6carasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        panContenido.add(btn6caras, gridBagConstraints);

        btn8caras.setBackground(new java.awt.Color(255, 204, 255));
        btn8caras.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btn8caras.setForeground(new java.awt.Color(51, 51, 51));
        btn8caras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dado-8caras.png"))); // NOI18N
        btn8caras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8carasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 39, 0, 0);
        panContenido.add(btn8caras, gridBagConstraints);

        btn10caras.setBackground(new java.awt.Color(255, 204, 255));
        btn10caras.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btn10caras.setForeground(new java.awt.Color(51, 51, 51));
        btn10caras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dado-10caras.png"))); // NOI18N
        btn10caras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10carasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 33, 0, 6);
        panContenido.add(btn10caras, gridBagConstraints);

        btn20caras.setBackground(new java.awt.Color(255, 204, 255));
        btn20caras.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btn20caras.setForeground(new java.awt.Color(51, 51, 51));
        btn20caras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dado-20caras.png"))); // NOI18N
        btn20caras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20carasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 38, 11, 0);
        panContenido.add(btn20caras, gridBagConstraints);

        btn12caras.setBackground(new java.awt.Color(255, 204, 255));
        btn12caras.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btn12caras.setForeground(new java.awt.Color(51, 51, 51));
        btn12caras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dado-12caras.png"))); // NOI18N
        btn12caras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12carasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 80, 11, 0);
        panContenido.add(btn12caras, gridBagConstraints);

        javax.swing.GroupLayout panLayout = new javax.swing.GroupLayout(pan);
        pan.setLayout(panLayout);
        panLayout.setHorizontalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panLayout.setVerticalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLayout.createSequentialGroup()
                .addComponent(panTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn6carasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6carasActionPerformed
        // TODO add your handling code here:
        mostrarNumero(6);
    }//GEN-LAST:event_btn6carasActionPerformed

    private void btn8carasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8carasActionPerformed
        // TODO add your handling code here:
        mostrarNumero(8);
    }//GEN-LAST:event_btn8carasActionPerformed

    private void btn10carasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10carasActionPerformed
        // TODO add your handling code here:
        mostrarNumero(10);
    }//GEN-LAST:event_btn10carasActionPerformed

    private void btn20carasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20carasActionPerformed
        // TODO add your handling code here:
        mostrarNumero(20);
    }//GEN-LAST:event_btn20carasActionPerformed

    private void btn12carasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12carasActionPerformed
        // TODO add your handling code here:
        mostrarNumero(12);
    }//GEN-LAST:event_btn12carasActionPerformed
    
    //------------------------- MÉTODOS DE CLASES ------------------------------
    public void mostrarNumero(int max) {
        txtResultado.setText("Número generado: " + Main.generarNumero(max));
    } // public void mostrarNumero(int max) {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10caras;
    private javax.swing.JButton btn12caras;
    private javax.swing.JButton btn20caras;
    private javax.swing.JButton btn6caras;
    private javax.swing.JButton btn8caras;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pan;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panTitulo;
    private javax.swing.JLabel txtResultado;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
