/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import logica.Main;

/**
 *
 * @author usuario
 */
public class Ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        pan = new javax.swing.JPanel();
        panTitulo = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        panContenido = new javax.swing.JPanel();
        txtSlider = new javax.swing.JLabel();
        jSlider = new javax.swing.JSlider();
        btn = new javax.swing.JButton();
        txtResultado = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pan.setBackground(new java.awt.Color(255, 255, 255));

        panTitulo.setBackground(new java.awt.Color(255, 204, 255));
        panTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTitulo.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(51, 51, 51));
        txtTitulo.setText("Números Aleatorios");
        panTitulo.add(txtTitulo);

        panContenido.setBackground(new java.awt.Color(255, 255, 255));

        txtSlider.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        txtSlider.setForeground(new java.awt.Color(51, 51, 51));
        txtSlider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSlider.setText("Valor máximo: ");

        jSlider.setMinimum(1);
        jSlider.setValueIsAdjusting(true);
        jSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderStateChanged(evt);
            }
        });

        btn.setBackground(new java.awt.Color(255, 204, 255));
        btn.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        btn.setForeground(new java.awt.Color(51, 51, 51));
        btn.setText("GENERAR");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        txtResultado.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(51, 51, 51));
        txtResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtResultado.setText("Número generado: ");

        javax.swing.GroupLayout panContenidoLayout = new javax.swing.GroupLayout(panContenido);
        panContenido.setLayout(panContenidoLayout);
        panContenidoLayout.setHorizontalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenidoLayout.createSequentialGroup()
                .addGroup(panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panContenidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panContenidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panContenidoLayout.createSequentialGroup()
                                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(panContenidoLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panContenidoLayout.setVerticalGroup(
            panContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panContenidoLayout.createSequentialGroup()
                .addComponent(txtSlider)
                .addGap(18, 18, 18)
                .addComponent(jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn)
                .addGap(18, 18, 18)
                .addComponent(txtResultado)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panLayout = new javax.swing.GroupLayout(pan);
        pan.setLayout(panLayout);
        panLayout.setHorizontalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panLayout.setVerticalGroup(
            panLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLayout.createSequentialGroup()
                .addComponent(panTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        txtResultado.setText("Número generado: " + Main.generarNumero(jSlider.getValue()));
    }//GEN-LAST:event_btnActionPerformed

    private void jSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderStateChanged
        // TODO add your handling code here:
        txtSlider.setText("Valor máximo: " + Integer.toString(jSlider.getValue()));
    }//GEN-LAST:event_jSliderStateChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider jSlider;
    private javax.swing.JPanel pan;
    private javax.swing.JPanel panContenido;
    private javax.swing.JPanel panTitulo;
    private javax.swing.JLabel txtResultado;
    private javax.swing.JLabel txtSlider;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
